<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PAON71K" ignored="0" name="Test3" tests="3" failures="1" timestamp="22 Sep 2019 07:43:38 GMT" time="4.176" errors="0">
  <testcase name="@AfterClass afterClass" time="0.012" classname="utilities.common_opps">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utilities.common_opps.afterClass(common_opps.java:292)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="Test001_verifyStudentCreated" time="2.482" classname="API_Tests.StudentsList_CRUD"/>
  <testcase name="Test002_verifyStudentUpdated" time="0.259" classname="API_Tests.StudentsList_CRUD">
    <failure type="java.lang.AssertionError" message="String NewLiel@gmail.com not exist inside the overall text, see details: java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: String NewLiel@gmail.com not exist inside the overall text, see details: java.lang.AssertionError: expected [true] but found [false]
at extensions.verify.contains(verify.java:130)
at API_Tests.StudentsList_CRUD.Test002_verifyStudentUpdated(StudentsList_CRUD.java:23)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test002_verifyStudentUpdated -->
  <testcase name="Test003_verifyStudentDeleted" time="0.121" classname="API_Tests.StudentsList_CRUD"/>
</testsuite> <!-- Test3 -->
